# Generated by Django 4.0.4 on 2022-05-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.IntegerField(null=True)),
                ('p_name', models.CharField(max_length=100, null=True)),
                ('c_name', models.CharField(max_length=100, null=True)),
                ('c_mail', models.CharField(max_length=100, null=True)),
                ('init_date', models.DateField(null=True)),
                ('ect', models.DateField(null=True)),
                ('status', models.DateField(null=True)),
                ('collabs', models.IntegerField(null=True)),
            ],
        ),
    ]
