# Generated by Django 4.0.4 on 2022-06-17 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_project_phase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='collabs',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='phase',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Inititated', 'Inititated'), ('Paused', 'Paused'), ('In progress', 'In progress'), ('Aborted', 'Aborted'), ('Completed', 'Completed')], default='Initiated', max_length=200, null=True),
        ),
    ]
