# Generated by Django 4.0.4 on 2022-06-18 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_project_collabs_alter_project_phase_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='status',
            new_name='p_status',
        ),
    ]
