# Generated by Django 4.0.4 on 2022-05-30 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_project_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='phase',
            field=models.ManyToManyField(to='accounts.phase'),
        ),
    ]
