# Generated by Django 4.0.4 on 2022-06-26 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_status_project_p_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='c_mail',
            new_name='client_mail',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='c_name',
            new_name='client_name',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='collabs',
            new_name='collaborations',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='init_date',
            new_name='date_initialised',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='p_name',
            new_name='project_name',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='p_status',
            new_name='project_status',
        ),
    ]
