# Generated by Django 4.0.4 on 2022-06-15 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_project_phase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
