# Generated by Django 4.0.4 on 2022-06-26 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_c_mail_project_client_mail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='date_initialised',
            new_name='project_initiated_on',
        ),
    ]
