# Generated by Django 4.0.4 on 2022-07-21 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_date_initialised_project_project_initiated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.CharField(choices=[('Initiated', 'Initiated'), ('Paused', 'Paused'), ('In progress', 'In progress'), ('Aborted', 'Aborted'), ('Completed', 'Completed')], default='Initiated', max_length=200, null=True),
        ),
    ]
